# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: CATALOG_DESCRIPTOR
    value: 'catalog.yaml'
  - name: ANYPOINT_ORG
    value: '67d9aaea-3ab0-4fb4-8f45-61f48c60c4f2'
  - name: ANYPOINT_ENV
    value: 'Sandbox'
  - name: ANYPOINT_HOST
    value: 'anypoint.mulesoft.com'
  - name: AWS_API_ID
    value: '0yfmyiql34'
  - name: API_FILE
    value: "api.json"
  - name: TMP_DIR
    value: 'xyz123'
  - name: VERSION
    value: '0'
  - group: anypoint-variable-group

trigger:
- master

pool: 
  name: "default"

steps:
- bash: |
    if [ -e $(CATALOG_DESCRIPTOR) ]
    then
      # Update catalog meta-data 
      mkdir -p $(TMP_DIR)
      
      if [ -d $(TMP_DIR) ]
      then 
        rm -rf $(TMP_DIR)
        mkdir $(TMP_DIR)
      fi 
      
      cat $(API_FILE)
      
      echo Environment
      env

      api-catalog update-descriptor 

      # Publish API      
      api-catalog publish-asset \
      --organization $(ANYPOINT_ORG) \
      --host=$(ANYPOINT_HOST) \
      --environment=$(ANYPOINT_ENV) \
      --client_id=$(ANYPOINT_CLIENT_ID) \
      --client_secret=$(ANYPOINT_CLIENT_SECRET) > catalog-result.txt
      
      cat catalog-result.txt
      
      # Capture latest version
      while IFS= read -r line
      do
        echo $line
        read -a strarr <<< $line
        if [[ "$line" == "Version"* ]]
        then
          VERSION="${strarr[1]}"
        fi
      done < catalog-result.txt

      echo Latest version $VERSION
      echo $VERSION > version.txt
    else
      exit 1
    fi
  env:
    ANYPOINT_CLIENT_ID: $(ANYPOINT_CLIENT_ID)
    ANYPOINT_CLIENT_SECRET: $(ANYPOINT_CLIENT_SECRET)
    ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
    ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)
  displayName: 'Catalog and validate'

- bash: |
    # Save ruleset for later
    cp openapi-best-practices-ruleset.yaml $(TMP_DIR)
    
    VERSION=$(<version.txt)
    
    echo Environment
    env

    # Download new asset
    anypoint-cli exchange asset download package-tracker-api/$VERSION $(TMP_DIR) \
        --organization $(ANYPOINT_ORG) \
        --host=$(ANYPOINT_HOST) \
        --environment=$(ANYPOINT_ENV)
  env:
    ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
    ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)
  displayName: 'Download asset from Exchange'

- bash: |
    # Validate API
    
    echo Environment
    env
    
    # Move and unzip file
    unzip -o $(TMP_DIR)/*.zip -d $(TMP_DIR)
    ls $(TMP_DIR)
    anypoint-cli governance api validate --rulesets  $(TMP_DIR)/openapi-best-practices-ruleset.yaml $(TMP_DIR)/*.zip \
    --organization $(ANYPOINT_ORG) \
    --host=$(ANYPOINT_HOST) \
    --environment=$(ANYPOINT_ENV) > output.txt
    
    cat output.txt
    
    # If output indicates error then stop
    if [[ ! $(grep "Spec conforms with Ruleset" output.txt) ]] ; then
        echo "Failed validation"
        exit 1
    else
        echo "Failed succeeded"
    fi
  env:
    ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
    ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)
  displayName: 'Validate against ruleset'

