# Example MuleSoft API cataloging and governance pipelinr

variables:
  - name: CATALOG_DESCRIPTOR
    value: 'catalog.yaml'
  - name: ANYPOINT_ORG
    value: '67d9aaea-3ab0-4fb4-8f45-61f48c60c4f2'
  - name: ANYPOINT_ENV
    value: 'Sandbox'
  - name: ANYPOINT_HOST
    value: 'anypoint.mulesoft.com'
  - name: API_FILE
    value: "api.json"
  - name: ASSET
    value: package-tracker-api
  - name: RULESET
    value: openapi-best-practices-ruleset.yaml
  # Include encrypted varialbles
  - group: anypoint-variable-group
  # Get branch
  - name: BRANCH_NAME
    value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]

trigger:
- master

pool: 
  name: "default"

stages:
- stage: publish_api
  displayName: Exchange
  jobs: 
  - job: catalog_api
    displayName: Catalog API
    steps:
    - bash: |
        if [ -e $(CATALOG_DESCRIPTOR) ]
        then      
          cat $(API_FILE)
          
          echo Environment
          env

          # Publish API      
          api-catalog publish-asset \
          --trigger-criteria=branch:$(BRANCH_NAME) \
          --organization $(ANYPOINT_ORG) \
          --host=$(ANYPOINT_HOST) \
          --environment=$(ANYPOINT_ENV) \
          --client_id=$(ANYPOINT_CLIENT_ID) \
          --client_secret=$(ANYPOINT_CLIENT_SECRET) > catalog-result.txt
          
          cat catalog-result.txt
          
          # Capture latest version
          while IFS= read -r line
          do
            echo $line
            read -a strarr <<< $line
            if [[ "$line" == "Version"* ]]
            then
              # Catpture version
              VERSION="${strarr[1]}"
              echo "##vso[task.setvariable variable=apiVersion;isOutput=true;]$VERSION"
              echo "Version value is $(VERSION)"
            fi
          done < catalog-result.txt

          echo Latest version $(apiVersion)
        else
          exit 1
        fi
      env:
        ANYPOINT_CLIENT_ID: $(ANYPOINT_CLIENT_ID)
        ANYPOINT_CLIENT_SECRET: $(ANYPOINT_CLIENT_SECRET)
        ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
        ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)
      name: catalog

  - job: validate_api
    displayName: Validate API
    dependsOn: ['catalog_api']
    variables: 
      apiVersion: $[ dependencies.catalog_api.outputs['catalog.apiVersion'] ]
    steps: 
    - bash: |
        # Validate API
        
        echo Environment
        env
        
        echo Version: $(apiVersion)

        # Download new asset
        anypoint-cli exchange asset download $(ASSET)/$(apiVersion) . \
          --organization $(ANYPOINT_ORG) \
          --host=$(ANYPOINT_HOST) \
          --environment=$(ANYPOINT_ENV)

        ls
        mv *.zip api.zip
        
        # Create zip asset to validate
        anypoint-cli governance api validate --rulesets  $(RULESET) ./api.zip \
        --organization $(ANYPOINT_ORG) \
        --host=$(ANYPOINT_HOST) \
        --output text \
        --environment=$(ANYPOINT_ENV) > governance.txt
        
        cat governance.txt
        
        # If output indicates error then stop
        if [[ ! $(grep "Spec conforms with Ruleset" governance.txt) ]] ; then
            echo "Failed validation"
        else
            echo "Failed succeeded"
        fi
      env:
        ANYPOINT_USERNAME: $(ANYPOINT_USERNAME)
        ANYPOINT_PASSWORD: $(ANYPOINT_PASSWORD)
      name: validate